refactor: UserAdmin page
hackforla/VRMS pull request #1059
Opened 2022-02-13 01:33 UTC by FoxShaunR

closes: https://github.com/hackforla/VRMS/issues/1053

Extracted all ui components into separate files along with their corresponding local state. Moved api-related code out of user admin components and into services. Refactored code and cleaned up linting issues throughout.

Made a few small functionality improvements too:
- Add "Project Name is Required" error message to Add New Project when user clicks "Add Project" without entering a name
- Moved error messages below Project Name field on Add New Project
- Improved search on

2022-02-14 01:17 UTC, drubgrubby requested changes
@FoxShaunR -> Really beautiful work!  Everything is nice and tidy and reusable and several levels above where it started.  It's a pleasure to look at,  and I learned a few things too.  So thanks for all of that. 

There's one error, and I probably wouldn't have found it if my parents hadn't named me "David". 

1) The error

When I'm on the user management, and using "Results by Name" and I enter the letter 'd' the app crashes.  I didn't check all of the other letters, but all of the other letters I checked worked fine.  Just "d".  I'm trying not to take it personally. 

<details>
<summary>Error image 1</summary>
<img width="1063" alt="Screen Shot 2022-02-13 at 5 00 51 PM" src="https://user-images.githubusercontent.com/68244054/153784310-40d14980-2671-4c10-bda3-8d71ef9ccc9e.png">
</details>

<details>
<summary>Error image 2</summary>
<img width="1081" alt="Screen Shot 2022-02-13 at 5 01 13 PM" src="https://user-images.githubusercontent.com/68244054/153784337-c521885c-3c25-409c-a104-d70d6a574cf3.png">
</details>

<details>
<summary>Error image 4</summary>
<img width="1056" alt="Screen Shot 2022-02-13 at 5 01 24 PM" src="https://user-images.githubusercontent.com/68244054/153784351-fff429e4-c07b-4840-a823-3a7a9f93e17d.png">

</details>

2022-02-15 02:31 UTC, FoxShaunR commented
Haha, quite the error. I'll take a look and see what's breaking

2022-02-15 15:32 UTC, drubgrubby approved these changes

2022-02-15 15:33 UTC, drubgrubby commented
That fixed it.  I guess it wasn't personal.  Ready to merge.

2022-02-15 15:33 UTC, merged