feat: Resolve most front-end warnings
hackforla/VRMS pull request #1298
Opened 2023-02-26 04:45 UTC by Spiteless

Fixes #1068 

### What changes did you make and why did you make them ?

Front end compiles with many warnings, this removes all but one of them at time of writing.

A few of the resolutions are //disable-next-line while we figure out if we want to drop some of the older features.

## Changes

<details>
<summary>Squashed Commit Messages:</summary>

asset: Update caniuse

fix: Remove useEffect from Auth, add onSubmit

Resolve Warning:
* Line 104:6:  React Hook useEffect has a missing dependency: 'handleLogin'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

fix: Add props.history to useEffect dep array

* Resolves Line 13:8:  React Hook useEffect has a missing dependency: 'props.history'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

fix: Add span and aria-label to eomji

fix: Remove useEffect, resolve no-unused-vars

in components:
* UserDashboard
* UserProfile
* ReturningUser
* Auth

fix: Add eslint ignore to recrutingDataFormatted

Code it references is currently commented out
Preserve until decision is made on to remove it or not

fix: Resolve no-self-assign warning in RosterTable

fix: Add ignore rule for gitHubClickHandler

fix: Remove unused vars event_city and event_state

fix: Add ignore rule for setCheckInReady

fix: Change .map to .forEach, no return needed

fix: Resolve no-throw-literal using new Error()

fix: Comment out console.log for backend

fix: Move true/false to prop vs new component

fix: Refactor single use fetch inside useEffect

Move fetch functions into useEffect to resolve react-hooks/exhaustive-deps

fix: Add props.location.search to deps array

Resolve react-hooks/exhaustive-deps

fix: Add auth to useEffect deps array

fix: Move fetch inside useEffect for eslint

* Add props to deps array to resolve react-hook/exhaustive-deps Resolves react-hooks/exhaustive-deps

fix: Move fetch inside useEffect for eslint

fix: Move fetch inside useEffect for eslint

fix: Rename headersToSend in import

Resolves warning for deps array, headersToSend is now defined outside the scope of the react component.

fix: Rename headersToSend in import

fix: Rename headersToSend in import

fix: Rename headersToSend in import

fix: Rename headersToSend in import

fix: Rename headersToSend in import

fix: Rename headersToSend in import

fix: Update useEffect react-hooks/exhastive-deps

Move single use functions inside useEffect
Add pieData to deps array

fix: Move single use function inside useEffect

Resolves react-hooks/ehxaustive-deps

</details>

<details>
<summary>Changes Before:</summary>
<img width="717" alt="image" src="https://user-images.githubusercontent.com/5898009/221392637-146cae6f-0ac8-4ae1-a57a-30e4a09dea4c.png">

</details>

<details>
<summary>Changes After:</summary>
<img width="717" alt="image" src="https://user-images.githubusercontent.com/5898009/221392602-bd7c3f1c-096b-4d93-9020-766246ac8b1e.png">
</details>

2023-02-27 20:24 UTC, MattPereira requested changes

2023-02-27 20:24 UTC, MattPereira commented on backend/workers/createRecurringEvents.js
> +        // console.log("Today's events are created");
My preference would be outright remove all of the `console.log()`s to keep things a bit more tidy but I'm open to discussion about it if you have a reason we should keep them as comments

2023-02-27 20:52 UTC, MattPereira commented
@Spiteless 

Really appreciate you grinding down so many of these errors for us

I tried passing in the dependency that last remaining console error is asking for and it crashed my browser. That `/components/admin/dashboard/index.js` file is a disaster lol

No features of the app are broken by this PR as far as I can tell, but we should still have another team member look at this for safety since there are so many files changed

My preference would be to decompose issues and PRs into smaller chunks to make it easier to confidently review the changes and be sure nothing is breaking

I'm willing to invest in someone like you who is clearly committed to grinding, but I also want to suggest that you might consider also joining the [hackforla/website](https://github.com/hackforla/website) team to learn about the kanban system that Bonnie has spent the last few years perfecting. The project does an amazing job teaching devs the fundamentals of github collaboration

2023-02-27 21:22 UTC, Spiteless commented
Yes, I tried getting the last one sorted out for about four days. I made
progress but not enough to resolve it completely. I had planned on asking
for help to get the last one resolved, but I’m not really sure it’s even
necessary because we might not use that component  at all within the
current iteration of VRMS.

Thanks for the vote of confidence on time investment. Would it have been
better to split this PR into similar chunks? For example, maybe 3 to 6 of
the resolutions to warnings were moving the definition of headersToSend
outside of the React component and another chunk was moving single use
fetch call within the usEffect hook rather than defining them outside the
hook.

In regard to joining the hackforla website team, I only have enough time
for one weekly evening meeting as it directly conflicts with my work
schedule (I work evenings and weekends). I am capable of following the
kanban system, what you’ve been seeing lately was me overcompensating for
not doing a  whole lot on the project prior to me getting my new work
computer.

If I’d be a better fit there that’s fine too, I’d like to get to the point
of being hireable so I can work less evenings :D

Anyhow, thanks for your focus and attention on my PRs, looking forward to
talking this evening.

On Mon, Feb 27, 2023 at 12:52 PM Matt Pereira ***@***.***>
wrote:

> @Spiteless <https://github.com/Spiteless>
>
> Really appreciate you grinding down so many of these errors for us
>
> I tried passing in the dependency that last remaining console error is
> asking for and it crashed my browser. That
> /components/admin/dashboard/index.js file is a disaster lol
>
> No features of the app are broken by this PR as far as I can tell, but we
> should still have another team member look at this for safety since there
> are so many files changed
>
> My preference would be to decompose issues and PRs into smaller chunks to
> make it easier to confidently review the changes and be sure nothing is
> breaking
>
> I'm willing to invest in someone like you who is clearly committed to
> grinding, but I also want to suggest that you might consider also joining
> the hackforla/website <https://github.com/hackforla/website> team to
> learn about the kanban system that Bonnie has spent the last few years
> perfecting. The project does an amazing job teaching devs the fundamentals
> of github collaboration
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackforla/VRMS/pull/1298#issuecomment-1447071122>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABM76GN75QW32FD5BXGDMWDWZUHZZANCNFSM6AAAAAAVIH27DY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-27 21:58 UTC, MattPereira commented
@Spiteless 

Yeah you are spot on with your idea to split the error fixes into groups. Ideally, you would create a new issue for each group of errors you are trying to solve and make a PR for each issue. That way you would also rack up the Github stats for creating issues and having multiple PRs merged and it would also make it easier for PR reviewers to assess the situation and if something did go wrong we would more easily be able to narrow it down to which merge broke something.

2023-02-28 04:40 UTC, Spiteless commented
Closing this PR to create smaller PRs with similar ESLint Warning resolutions

2023-02-28 04:40 UTC, closed without merging