Upgrade react scripts
hackforla/VRMS pull request #1326
Opened 2023-03-09 18:31 UTC by Spiteless

Fixes #1324

### What changes did you make and why did you make them ?
  - Move to react-scripts: ^5.0.1
    - Allows the current applicaton to run on node 18, 19
  - Add babel/core as dev dependency
  - Move images used by the app to client/src/assets to resolve import errors created from changing react-scripts versions.

Made this change to close a security vulnerabiltiy and to allow the current application to run on node 18+

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

<img width="356" alt="image" src="https://user-images.githubusercontent.com/5898009/224121177-7c0aa46d-e89a-4440-bc0c-03d6fc1c84dd.png">

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
<img width="356" alt="image" src="https://user-images.githubusercontent.com/5898009/224120557-8eca4ff3-b9d8-454b-8bf0-3e4d2b102c0c.png">

</details>

2023-03-10 06:22 UTC, MattPereira commented
@Spiteless You are my hero for creating and taking on this issue :heart: 

When I pulled down your branch for testing, I am getting a bunch of merge conflicts in the `yarn.lock` file located in the `client/` folder 

Could you try running `git pull vrms development` from the tip of the branch you created this PR using to see what happens?

2023-03-10 08:14 UTC, Spiteless commented
Interesting, I thought I branched off development and deleted the old lock
file. I’ll take a look tomorrow :/

On Thu, Mar 9, 2023 at 10:22 PM Matt Pereira ***@***.***>
wrote:

> @Spiteless <https://github.com/Spiteless> You are my hero for creating
> and taking on this issue ❤️
>
> When I pulled down your branch for testing, I am getting a bunch of merge
> conflicts in the yarn.lock file located in the client/ folder
>
> Could you try running git pull vrms development from the tip of the
> branch you created this PR using to see what happens?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackforla/VRMS/pull/1326#issuecomment-1463332432>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABM76GOSAQLM5A5EG2IJAELW3LCBRANCNFSM6AAAAAAVVPDUXU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-03-10 17:57 UTC, MattPereira commented
@Spiteless your PR is good the problem was on my end. I accidentally polluted my development branch. 

<img src="https://media4.giphy.com/media/w89ak63KNl0nJl80ig/giphy.gif"/>

2023-03-10 18:21 UTC, MattPereira commented
@ Trillium I am getting these `Can't resolve` errors for some of the images that are referenced in the `index.scss` file

<details><summary>See screenshot</summary>

![image](https://user-images.githubusercontent.com/73561520/224393265-3728f215-aec5-4301-8af0-bedcd4f7865a.png)

</details>


The app fires up perfectly if I update the `background-image` urls in the `index.scss` file

<details><summary>See screenshot</summary>

![image](https://user-images.githubusercontent.com/73561520/224393526-a6c212bd-83d7-46cd-bc37-313c22e1af36.png)


![image](https://user-images.githubusercontent.com/73561520/224393584-bd4f1b8e-f0a0-47f3-bf6a-e24cc559d275.png)

</details>

Since `index.scss` doesnt show up in the files changed of this PR, maybe you forgot to push up your latest commit ?

2023-03-10 19:23 UTC, Spiteless commented
It looks like I forgot to update the url import in the scss file. I’ll push
a commit to the branch to fix it

On Fri, Mar 10, 2023 at 10:22 AM Matt Pereira ***@***.***>
wrote:

> @ Trillium I am getting these Can't resolve errors for some of the images
> that are referenced in the index.scss file
> See screenshot
>
> [image: image]
> <https://user-images.githubusercontent.com/73561520/224393265-3728f215-aec5-4301-8af0-bedcd4f7865a.png>
>
> The app fires up perfectly if I update the background-image urls in the
> index.scss file
> See screenshot
>
> [image: image]
> <https://user-images.githubusercontent.com/73561520/224393526-a6c212bd-83d7-46cd-bc37-313c22e1af36.png>
>
> [image: image]
> <https://user-images.githubusercontent.com/73561520/224393584-bd4f1b8e-f0a0-47f3-bf6a-e24cc559d275.png>
>
> Since index.scss doesnt show up in the files changed of this PR, maybe
> you forgot to push up your latest commit ?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackforla/VRMS/pull/1326#issuecomment-1464201690>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABM76GK7QVS3MGKUL2EEY7LW3NWM7ANCNFSM6AAAAAAVVPDUXU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-03-10 19:27 UTC, Spiteless commented
I had built this in a separate local Paul request, and then re-create it
all the work in a clean branch, but forgot the SCSS file. I had built this
in a separate local poll request, and then re-created all the work in a
clean branch, but forgot the SCSS file excellent forensic analysis!

On Fri, Mar 10, 2023 at 11:22 AM Trillium ***@***.***> wrote:

> It looks like I forgot to update the url import in the scss file. I’ll
> push a commit to the branch to fix it
>
> On Fri, Mar 10, 2023 at 10:22 AM Matt Pereira ***@***.***>
> wrote:
>
>> @ Trillium I am getting these Can't resolve errors for some of the
>> images that are referenced in the index.scss file
>> See screenshot
>>
>> [image: image]
>> <https://user-images.githubusercontent.com/73561520/224393265-3728f215-aec5-4301-8af0-bedcd4f7865a.png>
>>
>> The app fires up perfectly if I update the background-image urls in the
>> index.scss file
>> See screenshot
>>
>> [image: image]
>> <https://user-images.githubusercontent.com/73561520/224393526-a6c212bd-83d7-46cd-bc37-313c22e1af36.png>
>>
>> [image: image]
>> <https://user-images.githubusercontent.com/73561520/224393584-bd4f1b8e-f0a0-47f3-bf6a-e24cc559d275.png>
>>
>> Since index.scss doesnt show up in the files changed of this PR, maybe
>> you forgot to push up your latest commit ?
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/hackforla/VRMS/pull/1326#issuecomment-1464201690>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ABM76GK7QVS3MGKUL2EEY7LW3NWM7ANCNFSM6AAAAAAVVPDUXU>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2023-03-10 20:04 UTC, Spiteless commented
@MattPereira Updated!

Compiles with warnging on the backend:

```
[1] [HPM] Proxy created: /  -> http://localhost:4000
[1] (node:59335) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
[1] (Use `node --trace-deprecation ...` to show where the warning was created)
[1] (node:59335) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
```

2023-03-10 20:07 UTC, Spiteless commented
Also sometimes compiles with this error:

```
[1] [eslint] ESLint configuration in ../.eslintrc is invalid:
[1]     - Unexpected top-level property "babelOptions".
[1] ERROR in [eslint] ESLint configuration in ../.eslintrc is invalid:
[1]     - Unexpected top-level property "babelOptions".
```

2023-03-10 23:00 UTC, MattPereira commented
Im so confused why app will sometimes start up and other times fail with an error

2023-03-12 04:00 UTC, MattPereira requested changes
@Spiteless I think this will fix the frontend not compiling because of invalid ESLint configuration. I've stopped and started several times and appears to be stable now

https://stackoverflow.com/questions/63428409/eslint-eslint-error-eslint-configuration-in-eslintrc-is-invalid

![image](https://user-images.githubusercontent.com/73561520/224523529-6583735f-c762-407f-9201-db564903103d.png)

2023-03-12 04:03 UTC, Spiteless commented
Appreciate the teamwork!

On Sat, Mar 11, 2023 at 8:00 PM Matt Pereira ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> @Spiteless <https://github.com/Spiteless> I think this will fix the
> frontend not compiling because of ESLint configuration. I've stopped and
> started several times and appears to be stable now
>
>
> https://stackoverflow.com/questions/63428409/eslint-eslint-error-eslint-configuration-in-eslintrc-is-invalid
>
> [image: image]
> <https://user-images.githubusercontent.com/73561520/224523529-6583735f-c762-407f-9201-db564903103d.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackforla/VRMS/pull/1326#pullrequestreview-1335961409>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABM76GJL4MJS6UEXNJPRHPTW3VC65ANCNFSM6AAAAAAVVPDUXU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-03-12 18:55 UTC, MattPereira approved these changes
@Spiteless this was really well executed from start to finish :+1: 

Love how you concisely explained the situation in the issue

And the way you crafted your PR creation comment made this one a pleasure to review

So glad to have you on the team! :tada:

2023-03-12 18:57 UTC, merged