asset: Update gitignore to ignore ./vscode
hackforla/VRMS pull request #1352
Opened 2023-03-20 23:39 UTC by Spiteless

Fixes #replace_this_text_with_the_issue_number

### What changes did you make and why did you make them ?
  - Add ignore for .vscode/ folder to allow for devs to set up their workspace however without effecting other devs

2023-03-21 18:33 UTC, MattPereira requested changes
> Fixes #replace_this_text_with_the_issue_number

@Spiteless please link issue number so that issue will be auto-closed when the PR gets merged

Also to help reviewers understand context of your requested changes

2023-03-28 02:28 UTC, Spiteless commented
@MattPereira Whoops, yes, I think I had it on edit and didn't submit

2023-03-28 17:26 UTC, MattPereira commented
@Spiteless 

I'm okay merging this since it sounds like its creating extra work not having it for you right now.

Just want to check in about the plan to eventually setup a common linter so that the formatting doesnt get whipped around by our different prettier settings

The stackoverflow you linked in the issue attached to this PR seems to indicate this is possible by using select files from the `.vscode` folder

![image](https://user-images.githubusercontent.com/73561520/228319830-2171ccc1-1efa-4d59-a1ef-3da92d0c798b.png)

2023-05-09 22:12 UTC, MattPereira approved these changes

2023-05-10 01:08 UTC, merged