Evn validation 1403
hackforla/VRMS pull request #1440
Opened 2023-07-17 06:01 UTC by evanyang1

Fixes #1403 

### What changes did you make and why did you make them ?

  -
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

2023-07-17 21:16 UTC, Spiteless commented
Hey Evan,

Can you add a bit of context on the changes you've made to the codebase and why they've been made?

I know that we have the issue markes, and that you've referenced them within this PR, but it's good practice to put a summary together so that whoever is reviewing it has an easier time following along with the changes you've submitted.

2023-07-19 00:14 UTC, Spiteless requested changes

2023-07-19 00:14 UTC, trillium commented on client/src/components/manageProjects/utilities/validateEventForm.js
> +            ['meeting', 'mtg', projectToEdit.name.toLowerCase()],
Nitpick but you don't need to pass in `.toLowerCase()` since then utils function you made already does that text transform

2023-07-19 00:14 UTC, Spiteless commented on client/src/components/manageProjects/utilities/validateEventForm.js
> +const validateEventForm = (vals, projectToEdit) => {
`CreateNewEvent()` fails because of this line

One solve is to have projectToEdit default to null `(vals, projectToEdit = null) =>`

2023-07-19 00:14 UTC, Spiteless commented on client/src/components/manageProjects/utilities/validateEventForm.js
> +            ['meeting', 'mtg', projectToEdit.name.toLowerCase()],
If using the above `projectToEdit = null` then you will also need to test this line to see if `projectToEdit` was suppied:
```js
['meeting', 'mtg', projectToEdit && projectToEdit.name.toLowerCase()]
```

2023-07-20 01:17 UTC, evanyang1 commented
@Spiteless I used a slightly different approach to address your comments. I tested it and it works still.

2023-07-27 23:12 UTC, jbubar approved these changes
This is great! I pulled it and it looks good
<details>
    <summary>pic of it live</summary>

<img width="573" alt="Screen Shot 2023-07-27 at 4 11 25 PM" src="https://github.com/hackforla/VRMS/assets/53061723/93f0f509-22b9-4c62-9ab6-e9c1f6963674">


</details>

2023-07-31 05:59 UTC, Spiteless commented
Hey @evanyang1 , looks like merging is blocked becasue I requested changes and haven't come back yet to remove that change request.

Glad to see you addressed getting the form submission issue that was cropping up.

Please remove your changes to `yarn.lock` from this pull request so we can get it merged :)

2023-07-31 08:52 UTC, evanyang1 commented
Ok that should do the trick.

2023-07-31 23:28 UTC, Spiteless commented
Great job, thanks for rebasing and dropping yarn lock. We've got a few PRs that all tackle this similar issue so stitching them together will be it's own beast, but this code works. Thanks @evanyang1 !

2023-07-31 23:28 UTC, Spiteless approved these changes

2023-07-31 23:29 UTC, Spiteless commented
Looking for a few more eyes on this if someone else has time. I'm happy with it's current state

2023-08-01 00:01 UTC, MattPereira approved these changes
@evanyang1 well done sanitizing the meeting name input according to the requirements of the issue!

2023-08-01 00:22 UTC, merged