Implement React Hook Form attrs
hackforla/VRMS pull request #1455
Opened 2023-07-30 23:02 UTC by bkmorgan3

Fixes #1387 

### What changes did you make and why did you make them ?

  - Implement React Hook Form attributes so it can control form inputs and check for validation errors
  - added regex check on Location inside SimpleInputs 
  -  added non-null validation on each input since each input is rendered via a Map call
  - displayed validation errors in red at the bottom of each input
  - Clean up ProjectAPI-Create call, removing unused properties and streamline req.body

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals after changes are applied</summary>
  
![Screenshot 2023-07-30 at 3 56 30 PM](https://github.com/hackforla/VRMS/assets/22487388/117e893f-5959-4028-a703-50f6c687f3ac)
Each Input has basic non-null validation

![Screenshot 2023-07-30 at 3 32 35 PM](https://github.com/hackforla/VRMS/assets/22487388/ae87d9b7-fdff-4197-b293-302de31fb6fe)

</details>

2023-07-31 04:13 UTC, Spiteless requested changes
Looking good, I like where these changes are going.

Requesting changes to
 * the location of the error text is displayed (move `<p>` to `helperText` prop - info in comments). 
 * validate form onBlur

Thanks for your hard work @bkmorgan3  :)

2023-07-31 04:13 UTC, trillium commented on client/src/components/ProjectForm.js
> -                  helperText=" "
Would be great to utilize MUI's helperText prop for TextArea here:

```js
<TextField
  helperText={errors[input.name]?.message || " "} //  This will keep spacing to prevent layout shift
  error={errors[input.name]?.message ? true : false}
  ...
/>

2023-07-31 04:13 UTC, trillium commented on client/src/components/ProjectForm.js
> +                <p style={{ color: '#fa114f' }}>{errors[input.name]?.message}</p>
Please drop this change and use the `helperText` prop from the above comment in line 255

2023-07-31 04:13 UTC, trillium commented on client/src/components/ProjectForm.js
> -                  id={input.name}
It would be great to validate the form on blur when the user navigates away from the form. Right now the form only validates the data on Submit, I think there's a way to have the form validate the data onBlur, but if there isn't an obvious way via  config object you can add the `onBlur` prop with a callback function.

```js
<TextArea
  onBlur={() => trigger(input.name)}
  ... 
/>

2023-08-01 00:53 UTC, bkmorgan3 commented on client/src/components/ProjectForm.js
> -                  id={input.name}
@Spiteless  fixed.

2023-08-01 00:54 UTC, bkmorgan3 commented on client/src/components/ProjectForm.js
> -                  helperText=" "
@Spiteless   fixed

2023-08-01 02:59 UTC, Spiteless commented
Notes from todays call:

@Spiteless
* Issue with rendering location (in-person) and location (remote)
* Advise making separate component that handles edge cases via props
* Still want to use current style of simpleInputs
* Want to be able to add validations to the simple input object
  * Can we add validations in an array that conform with react-hook-form validator object? [This page - search validate functions](https://www.react-hook-form.com/api/useform/register)

@bkmorgan3 mentioned blocker via slack on how to render location object. @Spiteless will play around with this to see if we can figure out how to render and validate that between the different location field types.

2023-08-04 19:17 UTC, bkmorgan3 commented
@Spiteless 
please review again.

2023-08-07 21:56 UTC, Spiteless approved these changes
Thanks Brad, happy to merge this PR :)

2023-08-07 22:40 UTC, merged