add new fields to edit project form
hackforla/VRMS pull request #1527
Opened 2023-10-11 20:19 UTC by bkmorgan3

Fixes #1489 

### What changes did you make and why did you make them ?

  - created new array in data.js representing the fields not displayed in the Model
 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<img width="483" alt="Screenshot 2023-10-11 at 1 16 18 PM" src="https://github.com/hackforla/VRMS/assets/22487388/927e0419-64a1-4407-8282-bdde9d32ac2c">

2023-10-16 22:47 UTC, Spiteless requested changes
Requested some changes on typos, information destructuring.

I think we also need to discuss if we want to let the user edit a field like `createdDate`

2023-10-16 22:47 UTC, Spiteless commented on client/src/components/manageProjects/editProject.js
> +        arr={[...simpleInputs, ...additionalInputsForEdit]}
In order for state to be passed to the form the info needs to be destructed off `projectToEdit`

```js
const [formData, setFormData] = useState({
    name: projectToEdit.name,
    description: projectToEdit.description,
    location: projectToEdit.location,
    githubIdentifier: projectToEdit.githubIdentifier,
    githubUrl: projectToEdit.githubUrl,
    slackUrl: projectToEdit.slackUrl,
    googleDriveUrl: projectToEdit.googleDriveUrl,
    hflaWebsiteUrl: projectToEdit.hflaWebsiteUrl,
    // ------ Need these fields to be destructured
    partners: projectToEdit.partners,
    managedByUsers: projectToEdit.managedByUsers,
    projectStatus: projectToEdit.projectStatus,
    googleDriveId: projectToEdit.googleDriveId,
    createdDate: projectToEdit.createdDate,
    // ------ 
  });

2023-10-16 22:47 UTC, Spiteless commented on client/src/components/data.js
> +    name: 'createdAt',
typo, correct field name is `createdDate`

2023-10-16 22:47 UTC, Spiteless commented on client/src/components/data.js
> +    name: 'mangedByUsers',
typo, correct field name is `managedByUsers`

2023-10-18 21:08 UTC, bkmorgan3 commented
> Requested some changes on typos, information destructuring.
> 
> I think we also need to discuss if we want to let the user edit a field like `createdDate`

@Spiteless  All things fixed.  I disabled the createdDate field.

2023-10-31 00:16 UTC, Spiteless approved these changes
Thanks for the updates, approved :)

2023-10-31 00:17 UTC, merged