feat: Flashing error message on server error
hackforla/VRMS pull request #1575
Opened 2024-02-05 05:55 UTC by freaky4wrld

Fixes #1569 

### What changes did you make and why did you make them ?

  -
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

2024-02-13 07:28 UTC, freaky4wrld commented on client/src/components/manageProjects/createNewEvent.js
>        await setTimeout(() => {
Maybe I can remove this whole block it's of no use I guess

```
await setTimeout (( ) => {
 .......
 }, 5000);
 
```

2024-02-13 07:58 UTC, freaky4wrld commented
@Spiteless the alert on recurring event has been provided, please have a look, also please tell what to do whether to update alert for `Event Updated/Event Deleted` for `severity=success` or let it as it is ?

2024-02-25 00:06 UTC, Spiteless requested changes
This is looking very good. Thank you for your hard work!

Requested a few small changes to create more clarity.

Very close to merging!

2024-02-25 00:06 UTC, Spiteless commented on client/src/components/manageProjects/editMeetingTimes.js
> +    showSnackbar("Event deleted!", 'warning');
Change text:

`Recurring event deleted`

Change level from `warning` -> `info`

2024-02-25 00:06 UTC, Spiteless commented on client/src/components/manageProjects/editMeetingTimes.js
> +      showSnackbar("Event updated!", 'info')
Change text:

`Recurring event updated`

2024-02-25 06:15 UTC, freaky4wrld commented
@Spiteless made the suggested changes, please check!!!

2024-02-25 09:17 UTC, Spiteless approved these changes

2024-02-25 09:18 UTC, merged