remove popup on the close button
hackforla/VRMS pull request #1616
Opened 2024-03-19 01:55 UTC by josiehandeveloper

Fixes #replace_this_text_with_the_issue_number

### What changes did you make and why did you make them ?
When the close button is pressed after the save button the popup is removed
  -
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

2024-03-22 19:24 UTC, Spiteless requested changes
This is looking great :)

Works as intended, thanks Jo!

There's a lot of style based changes happening here that don't have much to do with the PR though, we don't have any enforced ESLint/Prettier. I'm fine if we include them but it would be better if the changes are their own commit rather than blocked together with the `!editMode || ...` code change so that future people can see the relevant info faster.

Can you:
 - either:
   - [ ] switch the style changes to their own commit with a commit message like `style: Update code styling in ProjectForm.js`
   - [ ] Only commit the change directly relevant to the Close Edit Modal logic
 - [x] Delete the commented out code in the `<StyledButton>` tag 

Thanks for figuring this out!

2024-04-02 01:31 UTC, josiehandeveloper commented
I looked at the development branch to see what styling changes I made but I just changed the onClick portion of the code

2024-04-02 01:37 UTC, Spiteless commented
It's because we don't have linting across the project at this time (it's in the works). Your linter is formatting the file you're working on when you trigger save probably, which is resulting in a lot of small changes to the code such as changing `"thing"` --> `'thing'` etc. based on the linting rules your workspace has configured.

The file diff has a good representation of what's going on:
https://github.com/hackforla/VRMS/pull/1616/files

2024-04-16 01:59 UTC, Spiteless approved these changes
Thanks so much!

2024-04-16 01:59 UTC, merged