mui
hackforla/VRMS pull request #1732
Opened 2024-08-20 20:21 UTC by evanyang1

Fixes #1684 

### What changes did you make and why did you make them ?

replace with Material UI
(Blocked: Suggestions appreciated)

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

2024-11-10 20:38 UTC, pluto-bell requested changes
Several HTML components that still need to be switched over to MUI.

2024-11-10 20:38 UTC, pluto-bell commented on client/src/components/presentational/returnUserForm.jsx
>                  </button>
I believe the `<button>` components need to be switched to MUI as well.

2024-11-10 20:38 UTC, pluto-bell commented on client/src/components/presentational/returnUserForm.jsx
>                  </button>
Another `<button>` component to be switched over to MUI.

2024-11-10 20:38 UTC, pluto-bell commented on client/src/components/presentational/returnUserForm.jsx
>          >
`<form>` HTML component can be switched over to mui/material.

2024-11-10 20:38 UTC, pluto-bell commented on client/src/components/presentational/returnUserForm.jsx
>                </label>
`<label>` HTML component can be switched over to mui/material

2025-03-19 19:17 UTC, JackHaeg commented
Closing this PR, as a fresh PR has been submitted. Appreciate the work regardless :)

2025-03-19 19:17 UTC, closed without merging