Update newuser to mui
hackforla/VRMS pull request #1744
Opened 2024-09-14 23:36 UTC by awlFCCamp

Fixes #1720 

### What changes did you make and why did you make them ?

  - Replace standard HTML components with applicable MUI components.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

[image](
![Screenshot 2024-09-14 at 5 56 12 PM](https://github.com/user-attachments/assets/d453b521-68fb-4fe4-99e8-fdf2478e7f07)
)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
[image](
![Screenshot 2024-09-14 at 6 30 52 PM](https://github.com/user-attachments/assets/b521c819-d077-48a2-8982-010f4d07774a)
)

</details>

2024-09-16 18:00 UTC, bkmorgan3 commented
@awlFCCamp  did you delete the bot instructions for checking out this branch?

2024-09-16 18:06 UTC, awlFCCamp commented
"@bkmorgan3 I don't think I did. Are you referring to one of the GitHub Actions being deleted? I only modified and pushed one file. didn't do anything in .github.

2024-09-16 18:23 UTC, awlFCCamp commented
@bkmorgan3 you are concerning my "Add Pull Request Instructions..." failed? here is the error message"Current runner version: '2.319.1'
Operating System
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: None
Prepare workflow directory
Prepare all required actions
Getting action download info
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v[2](https://github.com/hackforla/VRMS/actions/runs/10866337611/job/30211631317?pr=1744#step:1:2)`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/" We need upgrade it to v3. Hope I am correct here. @trillium can you chime in? Thank you!

2024-09-17 02:44 UTC, jbubar requested changes, later dismissed
@awlFCCamp Requesting we keep the Css in the css files. can you use the class name

2024-09-24 01:28 UTC, trillium commented
> @bkmorgan3 You were concerned my "Add Pull Request Instructions ..." didn't get run. In one of the yml files we need to change ` uses: actions/upload-artifact@v2` to ` uses: actions/upload-artifact@v3` Hope I am correct here. @trillium can you chime in? Thank you!

You probs are correct, will check on if there's an issue for this

2024-09-24 01:54 UTC, bkmorgan3 commented
@trillium  No, no.  Its just new UI I am not used to seeing.  I just needed to click View Command Line Instructions under the tests module.  All good

2024-09-24 01:56 UTC, trillium commented
Ah, gottcha. Regardless, we've currently got some errors in our github toolchain.

2024-09-24 14:53 UTC, nora-zajzon approved these changes
Website looks the same as the screenshots she provided. All html are now mui. Looks good!

2025-06-17 02:59 UTC, trillium approved these changes
Long time coming but we're approving this!

2025-06-17 02:59 UTC, merged