adapt ValidatedTextField to accept custom validation functions
hackforla/VRMS pull request #1789
Opened 2024-10-14 18:36 UTC by angela-lee1

Fixes #1484

### What changes did you make and why did you make them ?

  - Adapt ValidatedTextField to apply custom validations into the validate portion of the register function from react-hook-form
 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

[image]()

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
[image](
![Screenshot 2024-10-14 at 1 35 26 PM](https://github.com/user-attachments/assets/a184cf4b-5546-4731-a86d-2beaf8726f4a)
)

</details>

2024-11-10 20:20 UTC, pluto-bell requested changes
@angela-lee1 it looks like one of your changes caused a change on styling as well.
<details><summary>Before and After</summary>
Notice how the form was previously encapsulated by the same grey background as the section above it and included different padding/margin. 

<img width="693" alt="Screenshot 2024-11-10 at 12 03 12 PM" src="https://github.com/user-attachments/assets/967eda95-4c21-4158-8761-656b241612a1">
<img width="675" alt="Screenshot 2024-11-10 at 12 03 28 PM" src="https://github.com/user-attachments/assets/2cc38d40-6748-44fb-9e20-48d1a84d4fe6">
</details>

<details><summary>Potential Cause</summary>
It looks like the `form` component got removed as a child from a `div` component with a `MuiBox-css` class. Notice how the `form` component was previously nested 

<img width="1389" alt="Screenshot 2024-11-10 at 12 07 11 PM" src="https://github.com/user-attachments/assets/1ccaf183-3008-4160-b762-926a346a2d25">
<img width="1433" alt="Screenshot 2024-11-10 at 12 10 00 PM" src="https://github.com/user-attachments/assets/6d9502cc-8523-4391-9edb-4b860f1d94f0">



</details>

2025-01-31 00:41 UTC, JackHaeg commented
@angela-lee1 Just checking in on this PR! Were you able to address the concerns that @pluto-bell mentioned in her review above?

2025-01-31 00:55 UTC, angela-lee1 commented
@JackHaeg will get this resolved before next team meeting. Sorry.

2025-02-04 01:24 UTC, JackHaeg commented
No problem, @angela-lee1! Thanks in advance for working on this!

2025-02-11 02:45 UTC, JackHaeg commented
Hi @angela-lee1 Just checking in on this PR :) 

**When you have a moment, can you please provide an update with the following information:**
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."
  - remember to add links to the top of the issue if they are going to be needed again.

2025-02-12 02:24 UTC, angela-lee1 commented
@JackHaeg I am terribly sorry. I don't have any blockers. I will get it done by this Friday at the end of the day.

2025-02-12 03:03 UTC, JackHaeg commented
Hi @angela-lee1 No worries at all - seriously!! Thanks so much for confirming and for making these updates to the PR :)

2025-02-25 02:10 UTC, JackHaeg commented
@angela-lee1 Just checking in since I saw an the additional commit submitted last week. Is this PR ready for review? 

Based on your last comment, it sounds like you might just need Trilliums assistance with the merge conflicts, correct?

2025-02-25 03:25 UTC, JackHaeg commented
Per @angela-lee1 this PR is ready for review.

2025-08-19 02:57 UTC, JackHaeg commented
@angela-lee1 To resolve merge conflicts

2025-09-11 20:17 UTC, JackHaeg commented
Hi @angela-lee1 - Just checking in! Can you please provide an update on when you believe these merge conflicts will be addressed?

2025-09-11 22:19 UTC, angela-lee1 commented
@JackHaeg, I got sick last weekend, sorry about procrastinating. I was planning to use last weekend for this. Yes, I will work on it tonight or tomorrow night. The ETA is September 13th.

2025-09-23 01:27 UTC, JackHaeg commented
Hi @angela-lee1 just checking in on this PR :) Whenever you have a moment, can you please resolve these merge conflicts so that we can merge this PR?

2026-02-03 02:07 UTC, trillium approved these changes
## Review: Approve

**Summary:** This PR enables custom validation functions in ValidatedTextField by passing `input.validate` directly to react-hook-form's register function. Clean, simple implementation.

### Changes Reviewed
- ✅ `ValidatedTextField.jsx`: Adds `input.validate` passthrough to react-hook-form
- ✅ `ProjectForm.jsx`: Adds Paper wrapper to fix styling regression

### Notes
- Custom validation implementation follows react-hook-form conventions
- Paper wrapper fixes the grey background issue noted in previous review
- `required` logic changed to default-required (`!== false`) - verify existing forms still work

### Testing Recommended
- Visual verification that form styling matches design (grey background)
- Manual test of custom validation if any forms use it

Rebased onto `upstream/development` - ready to merge after push.

2026-02-03 02:09 UTC, merged