add form validation for zoom google meet
hackforla/VRMS pull request #1812
Opened 2024-11-13 03:19 UTC by angela-lee1

Fixes #1511 

### What changes did you make and why did you make them ?

  - modify validateLink for Zoom and Google meet link
  - Zoom and Google Meet links are validated at create new recurring event

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](
![Screenshot 2024-11-12 at 2 22 43 PM](https://github.com/user-attachments/assets/d87b94e6-1ae6-4c10-87e5-4bea1d9da910)
)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](
![Screenshot 2024-11-12 at 8 55 18 PM](https://github.com/user-attachments/assets/a2cdcf91-14cf-4586-866b-2ec8eb5fb33b)
)

</details>

2024-11-18 00:32 UTC, nora-zajzon requested changes
I am having trouble getting approved links to work. I tried with both google meet and zoom and both of them seem to return Invalid Link. I could be the one doing it wrong but I am not sure how else to try.
<img width="508" alt="Screenshot 2024-11-17 at 4 29 39 PM" src="https://github.com/user-attachments/assets/58a5289c-aa2a-4e08-a44c-06a0f03ff09e">
<img width="490" alt="Screenshot 2024-11-17 at 4 30 19 PM" src="https://github.com/user-attachments/assets/e8cae62e-d7d7-4e34-8e0a-e93decf4c4de">

2024-11-18 00:48 UTC, angela-lee1 commented
@nora-zajzon, did you have a link like https://meet.google.com/bgc-szbm-osr? I was able to add it.
![Screenshot 2024-11-17 at 6 46 19 PM](https://github.com/user-attachments/assets/652ba379-e01e-4a58-8452-8767d1b5ad19)
![Screenshot 2024-11-17 at 6 46 14 PM (2)](https://github.com/user-attachments/assets/1bd15056-7920-4e49-baae-27c7f07bc226)

2024-11-19 02:54 UTC, trillium commented
## Do we allow users to enter relative URLs (those that omit https://)?

Yes, please allow for the `https://` to be ommitted, as well as `www.`

## Also, do we permit users to use Zoom meeting URLs with subdomains? 

Also yes

Thanks for asking for clarification!

2025-01-26 21:11 UTC, angela-lee1 commented
@trillium I made the requested changes and updated the branch. Can you please take a look at the branch? Thanks

2025-02-07 19:45 UTC, dannyprikaz approved these changes
Looks good. The new regex lets the user input zoom or google links with or without 'https://'.

2025-03-06 22:50 UTC, JackHaeg commented
To any reviewers & @angela-lee1 - it looks like there are merge conflicts that must be resolved in order to move ahead with merging this PR. Please address these conflicts when time permits.

2025-05-15 22:07 UTC, JackHaeg commented
Hi @angela-lee1!  

Whenever you have a moment, please resolve these merge conflicts with this PR and then we can go ahead and merge :)

2025-05-19 19:14 UTC, merged