EventTemplate model added
hackforla/VRMS pull request #367
Opened 2020-10-28 21:25 UTC by awhig

2020-10-29 00:02 UTC, nickbeaird requested changes

2020-10-29 00:02 UTC, nickbeaird commented on backend/models/eventTemplate.test.js
> +    expect(savedData.startTime === submittedData.startTime);
Tests need to be reviewed. See if you are getting accurate output. Jest requires the toBe() syntax.

2020-10-29 00:21 UTC, awhig commented on backend/models/eventTemplate.test.js
> +    expect(savedData.startTime === submittedData.startTime);
Done.

2020-11-02 18:00 UTC, alex-anakin approved these changes
Approved.

2020-11-02 18:01 UTC, merged