#322 implement create account page
hackforla/VRMS pull request #402
Opened 2020-11-10 00:32 UTC by ChrxsCrxss

Fixes #322.

2020-11-10 19:12 UTC, OlgaBilogurova requested changes
Hey @ChrxsCrxss , 

Please, pull changes from `development` branch and resolve conflicts by:
- applying changes from development branch for `components/common/button/button.js`
- applying your changes + changes from development branch for `routes/index.js`

Because tasks #386 and #322 have pretty similar functionality. It will be great to reuse code, utils, and service from merged PR #401.

Please, reuse:
- `utils/validation.js` to validate email
- `services/user.service.js` to fetch data from API
- existing components `<Title /> , <Buttont />, <Input />, <ErrorMessage /> `

Also, please rename the component name on CreateAccount, and path on `/create-account`. Because in [MVP (v0.4) Requirements](https://docs.google.com/document/d/16VvC0fbaXsvEQkQaVSj8dG3wFEHgErbjJ6H3akSUoVM/edit#heading=h.noikk67a6ft2) this page name's `Create Account`.

Please, let me know if you have any questions. And after applying these changes I'll provide a full code review.

2020-11-10 19:12 UTC, OlgaBilogurova commented on client-mvp-04/src/routes/index.js
> +    component: Register,
In MVP (v0.4) Requirements page name is `Create Account`. 

Let's change on:
    path: '/create-account',
    key: 'create-account',
    component: CreateAccount,

2020-11-13 15:42 UTC, ChrxsCrxss commented
Hey @OlgaBilogurova ,

I have completed everything above. However, there is an issue. When I use services/user.service.js to fetch data from API, I get a 401 error response even though the custom request header is included in the request. I checked the network request headers, and it shows x-customrequired-header as undefined. This is the case for fetches from the login page and createAccount page.

2020-11-14 06:28 UTC, OlgaBilogurova commented
@ChrxsCrxss , x-customrequired-header exists in `user.service.js`:
https://github.com/hackforla/VRMS/blob/1313f08212f8692935b20c52915b1b1a9978fc23/client-mvp-04/src/services/user.service.js#L1-L4
Please, update your .env variables and make sure that you have file `src/setupProxy.js`.
Everything works for me. Please, let me know if it works for you.

2020-11-14 06:53 UTC, OlgaBilogurova requested changes

2020-11-14 06:53 UTC, OlgaBilogurova commented on backend/app.js
> +app.use(cors());
We shouldn't allow CORS for all APIs, so please remove changes from backend/app.js.

2020-11-15 02:24 UTC, OlgaBilogurova commented
@ChrxsCrxss , 
I pulled your changes, installed npm modules with `yarn install`, and added env. vars.
Then I run `client-mvp-04` and everything works for me. 

I'm able to fetch data from API for `Login` and `CreateAccount` pages.

I just removed a line: 
`props.dispatch(setUser(userData));` 
because you don't need to store data. But even with dispatch, I got data from API with the error at the end.

https://drive.google.com/file/d/1O2Jk8UhHUdeyQJr7VCL61IwvTRv0UWZf/view?usp=sharing

Please, double-check .env (for backend, client, client-mvp-04) and reinstall npm modules (for root, backend, client, client-mvp-04). If it still doesn't work, let's set up a meeting on Monday.

2020-11-15 03:24 UTC, OlgaBilogurova requested changes
@ChrxsCrxss , please, resolve my comments or response if you have another opinion.

Also, it would be great to cover CreateAccountContainer functionality with tests. You can create a separate task for this.

Please, use prettier locally during development. It helps to automate the cleanup, spacing of code, typos, empty line at the end of the file, and all code formatting.

2020-11-15 03:24 UTC, OlgaBilogurova commented on backend/app.js
> +const cors = require('cors');
Remove this line also.

2020-11-15 03:24 UTC, OlgaBilogurova commented on client-mvp-04/src/components/createAccount/createAccountContainer.js
> +      if ( ! userData ) {
Please, remove space between ! and userData:
`if ( !userData ) {`

2020-11-15 03:24 UTC, OlgaBilogurova commented on client-mvp-04/src/components/createAccount/createAccountView.test.js
> +
Remove this empty line

2020-11-15 03:24 UTC, OlgaBilogurova commented on client-mvp-04/src/components/createAccount/createAccountView.test.js
> +});
Add one line at the end. Always, should have an empty line at the end.

2020-11-15 03:24 UTC, OlgaBilogurova commented on client-mvp-04/src/components/createAccount/createAccountContainer.js
> +export default CreateAccountContainer;
Add one line at the end. Always, should have an empty line at the end.

2020-11-15 03:24 UTC, OlgaBilogurova commented on client-mvp-04/src/components/createAccount/createAccountContainer.js
> +        props.dispatch(setUser(userData));
Please, remove this line because you don't need to store data in redux store.
And if so, you should connect the component to the store. Currently, it doesn't work.

2020-11-15 03:24 UTC, OlgaBilogurova commented on client-mvp-04/src/components/createAccount/createAccountContainer.js
> +import { connect } from 'react-redux';
Remove unused import { connect } from 'react-redux'

2020-11-15 03:24 UTC, OlgaBilogurova commented on client-mvp-04/src/components/createAccount/createAccountContainer.js
> +        // user is not registered in app, redirect to dummny page
Typo: In word 'dummny' => dummy page

2020-11-15 03:24 UTC, OlgaBilogurova commented on client-mvp-04/src/components/createAccount/createAccount.scss
> +    color: blue;
Why color is blue?
In Figma mockup color is #2F80ED, and we have _colors.scss variables 
for this color variable is $accent-royal-blue-color
And please, apply all styles for this button from Figma mockup.

2020-11-15 03:24 UTC, OlgaBilogurova commented on client-mvp-04/src/components/createAccount/createAccountContainer.js
> +import { setUser } from '../../store/actions/userActions';
Remove this import, please also

2020-11-15 03:24 UTC, OlgaBilogurova commented on client-mvp-04/src/components/createAccount/createAccountContainer.js
> +        // user is already registered in app, update global state in store
Remove this line

2020-11-15 03:24 UTC, OlgaBilogurova commented on client-mvp-04/src/components/createAccount/createAccountView.js
> +            className={'createAccount-button'}
All classes should be named using kebab-case style.
As `create-account-button`

2020-11-15 03:24 UTC, OlgaBilogurova commented on client-mvp-04/src/components/createAccount/createAccountView.js
> +        <section data-testid="createAccount" className="createAccount-container">
All classes and data-testid should be named using kebab-case style: `create-account-container`

2020-11-17 02:38 UTC, OlgaBilogurova approved these changes

2020-11-17 02:44 UTC, OlgaBilogurova commented
@alex-anakin merge, please.

2020-11-17 02:53 UTC, merged