Create ModificationLog schema/model/test
hackforla/VRMS pull request #406
Opened 2020-11-10 06:46 UTC by awhig

2020-11-15 21:37 UTC, nickbeaird requested changes

2020-11-15 21:37 UTC, nickbeaird commented on backend/models/modificationLog.model.js
> +    objectId: { type: String }, // modified object id stored as String
What is the purpose of this field? It seems like from the test that this is a primary key and an integer, but it looks to be a string here. Also, this seems redundant as we already have a n id provided by mongo. I may have some follow up depending on what approach you are taking.

2020-11-15 22:46 UTC, alex-anakin approved these changes
Looks good! Approved.

2020-11-15 22:49 UTC, alex-anakin commented on backend/models/modificationLog.model.js
> +    objectId: { type: String }, // modified object id stored as String
It's an id of the saved object that was modified, not the id of the model.

2020-11-15 22:56 UTC, alex-anakin requested changes
Sorry, after rerunning tests with applied changes the test https://github.com/hackforla/VRMS/blob/development/backend/routers/auth.router.test.js failed. Take a look at https://github.com/hackforla/VRMS/pull/406/checks?check_run_id=1403766863
We need to clean the test DB between test cases running or to use different emails.
Please fix.

2020-11-16 20:04 UTC, awhig commented
@alex-anakin I reran the test jobs, and got a different error than the previous run. I fixed those in the PR and it now passes.

2020-11-17 02:07 UTC, nickbeaird approved these changes

2020-11-17 18:19 UTC, alex-anakin approved these changes

2020-11-17 18:19 UTC, merged