Magic link / Add auth origin payload
hackforla/VRMS pull request #492
Opened 2021-02-17 08:03 UTC by OlgaBilogurova

Fixes #471 

@alex-anakin please, review especially backend changes I made for this issue.
I completed all action items from the task besides the last one:
"Send auth_origin back to the frontend in both cases of success or failure."
Currently, in case of failure, the backend sends status `res.sendStatus(400)` or `res.sendStatus(401)`. What changes do you want me to do there?

2021-02-23 04:42 UTC, alex-anakin requested changes
Please make changes to the old client:
1. Send `LOG_IN` when requesting authorization.
2. Parse changed the magic link response properly.
3. Test logging in on the old client.

2021-02-23 04:42 UTC, alex-anakin commented on backend/controllers/user.controller.js
> +    console.log(payload);
please remove it

2021-04-20 02:57 UTC, peteplass commented
Reviewed in meeting - would like update by 4/26

2021-05-04 01:32 UTC, OlgaBilogurova commented
This week I'm going to make changes for this PR.

2021-05-11 01:22 UTC, OlgaBilogurova commented
Update:
- Resolved comment
- Reworked `auth` logic for `AdminLogin` component for the old client to have login functionality working (for admin user role).
- Merged changes from `development `and have 1 backend test failing.

I'm going to refactor and rename this component, and probably extract API requests to a separate file.
Will do it this week.

2021-05-11 01:44 UTC, alex-anakin approved these changes
Looks good to me

2021-05-11 01:44 UTC, merged