Current skills component
hackforla/VRMS pull request #595
Opened 2021-06-22 02:06 UTC by jbubar

Here is my best attempt to resolve #479
Let me know how I can improve this component, or add any features

2021-06-22 02:16 UTC, jbubar commented
<details>
    <summary>gif of the thing</summary>

![skillthing](https://user-images.githubusercontent.com/53061723/122852239-253bd300-d2c5-11eb-92a4-f807abb23b88.gif)


</details>

2021-06-22 22:20 UTC, drubgrubby requested changes
@jbubar -> Really nice work!  This is a really full functioned feature that seems to work really well and was fun to test.  I have, of course, a few change requests nonetheless.

2021-06-22 22:20 UTC, drubgrubby commented on client-mvp-04/src/components/common/inputSkills/inputSkills.js
> +  // const [skills, setSkills] = useState([]);
Remove commented out hook...unless that's going to be put into service later.

2021-06-22 22:20 UTC, drubgrubby commented on client-mvp-04/src/utils/uiKit/uiKit.js
> +
Add descriptor: "Current skills input" (or some such)

2021-06-22 22:20 UTC, drubgrubby commented on client-mvp-04/src/components/common/inputSkills/inputSkills.js
> +    );
When it's matching skills to input it should match to the first letter of the skill.  It seems like it's matching if it includes the letter at all: 

<img width="453" alt="Screen Shot 2021-06-22 at 2 37 32 PM" src="https://user-images.githubusercontent.com/68244054/123003414-03dff300-d368-11eb-8726-c33a4e2611a1.png">

2021-06-22 22:20 UTC, drubgrubby commented on client-mvp-04/src/components/common/inputSkills/inputSkills.js
> +        <PlusSign onClick={submitSkill} className="input-plus" />
Is it possible to have the input add when hitting the "enter" key so you don't have to hit the plus sign?  It works fine with the plus sign, but it did take me a sec to realize that I had to hit the plus sign to add the skill.

2021-06-22 22:20 UTC, drubgrubby commented on client-mvp-04/src/components/common/inputSkills/inputSkills.js
> +                input.parentElement.classList.add('required-asterisk');
It seems like the asterisk should disappear if there are any skills already added to the list.  Not a big deal, but it seems like it should only bug you that it's a required field if you haven't entered anything.

2021-06-22 22:20 UTC, drubgrubby commented on client-mvp-04/src/components/common/inputSkills/inputSkills.js
> +  }
It should remove the old error when someone does a subsequent input, whether it created another error or not. Now it seems to just stack the errors, which makes me feel like I can't do anything right.

<img width="480" alt="Screen Shot 2021-06-22 at 2 49 15 PM" src="https://user-images.githubusercontent.com/68244054/123004490-80bf9c80-d369-11eb-9d26-6f39231e1ad2.png">

I'd also change the error to something like: "X is not a valid input. Please select from the dropdown list."

2021-06-25 01:23 UTC, jbubar commented on client-mvp-04/src/components/common/inputSkills/inputSkills.js
> +                input.parentElement.classList.add('required-asterisk');
Ohh! that makes sense 
and a lot simpler than what I put

2021-06-25 01:59 UTC, jbubar commented on client-mvp-04/src/components/common/inputSkills/inputSkills.js
> +  // const [skills, setSkills] = useState([]);
Thanks! did it

2021-06-25 02:00 UTC, jbubar commented on client-mvp-04/src/utils/uiKit/uiKit.js
> +
Changed this! thanks

2021-06-25 02:00 UTC, jbubar commented on client-mvp-04/src/components/common/inputSkills/inputSkills.js
> +    );
DOne

2021-06-25 02:00 UTC, jbubar commented on client-mvp-04/src/components/common/inputSkills/inputSkills.js
> +                input.parentElement.classList.add('required-asterisk');
done

2021-06-25 02:00 UTC, jbubar commented on client-mvp-04/src/components/common/inputSkills/inputSkills.js
> +  }
done

2021-06-25 02:01 UTC, jbubar commented on client-mvp-04/src/components/common/inputSkills/inputSkills.js
> +        <PlusSign onClick={submitSkill} className="input-plus" />
yes.. did it!

2021-06-30 20:12 UTC, drubgrubby approved these changes
@jbubar -> This looks great.  Thanks for making those changes.  Nice work!

2021-06-30 20:13 UTC, merged