Changes per meeting with Ops team - Closes #624
hackforla/VRMS pull request #625
Opened 2021-07-22 04:50 UTC by jasonwong26

Met with Darren and the Ops team, and they asked for a few changes so they can move forward with hosting v0.3:

- Provide them with all necessary ENVIRONMENT variables (DONE)
- Convert settings for `MailHog` to ENVIRONMENT variables
- Set up new Production specific Docker files (`backend/Dockerfile.prod` and `client.Dockerfile.prod`)
- Create a set of health check pages (`/healthcheck` and `api/healthcheck`)

## New Environment Variables for MailHog
These changes require the following be added to the backend `.env` file:

```
MAILHOG_PORT=1025
MAILHOG_USER=user
MAILHOG_PASSWORD=password
```

We'll also want to update the Environment variables document once these changes are approved.

## New Docker Files for Dev

- `backend/Dockerfile.dev`
-  `client.Dockerfile.dev`

Darren recommended that we simplify the Dev environment with these (to replace the original `.api` and `.client` files), however I got `nginx` errors when I tested them.  
I kept them in this PR for reference, but we'll need additional changes to convert over.

2021-07-22 05:12 UTC, jasonwong26 commented
@alex-anakin, @mrao2 

I went ahead and added the environment variables to the Repository Secrets and PR Validation Workflow, but the ` test-backend-integration` still fails, reporting missing variables.

Do either of you know what I'm missing?  I need to stop for the night.

2021-07-23 07:24 UTC, alex-anakin requested changes
Everything is fine except for a couple of missed new lines at the end of the file.

2021-07-23 07:24 UTC, alex-anakin commented on backend/Dockerfile.dev
> +COPY . .
please, add an empty line at the end of the file
https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

2021-07-23 07:24 UTC, alex-anakin commented on backend/controllers/healthCheck.controller.js
> +module.exports = HealthCheckController;
please, add an empty line at the end of the file
https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

2021-07-23 07:24 UTC, alex-anakin commented on client/Dockerfile.dev
> +RUN npm install --silent
please, add an empty line at the end of the file
https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

2021-07-23 07:41 UTC, alex-anakin commented
@jasonwong26 Could you try please to close this PR and create a new one? For me, it seems like the PR "remembers" the state of actions that were run for it from the beginning. And it does not refresh the state after updating the action.

2021-07-23 21:00 UTC, jasonwong26 commented
Per @alex-anakin request, will close and reopen this PR.

2021-07-23 21:00 UTC, closed without merging