Manage Project Feature: Edit project info
hackforla/VRMS pull request #671
Opened 2021-08-13 18:10 UTC by drubgrubby

closes #571 

By clicking the "Projects" navigation link you can select a project, and edit all of the project information stored under that project.  (This does not include meetings and other recurring events, which will be covered in the next issue). 

This is obviously not beautiful and could use some design and styling, but I believe the functionality is there.  If the team wants to spend resources on beautifying this feature after it's complete, then I suggest we do all of the design and styling at the end rather than doing it piecemeal. 

Note: The 'goFetch' function is something I was working on that I may use in refactoring some of the code in this module.  I'm just adding it in this PR even thought it's not in use yet. 

Special shout-out to @jbubar for the awesome editableField component that we used to build this.

2021-08-17 05:47 UTC, jbubar requested changes
Just a few small things that you could address, or ignore.. I might also need some updated .env variables or something? Could not get it to run because the user was underfined.
![Screen Shot 2021-08-16 at 10 43 38 PM](https://user-images.githubusercontent.com/53061723/129670175-465f7b73-3888-4cdd-8612-39d7751ba4ca.png)

2021-08-17 05:47 UTC, jbubar commented on client/src/utils/fetchUtils.js
> +      if () {
Is this empty if() statement a typo?
Wondering how it does not seem to break stuff

2021-08-17 05:47 UTC, jbubar commented on client/src/sass/ManageProjects.scss
> +.editable-field {
try `div .editable-field {` as a css selector.. that way you dont have to use important

2021-08-17 05:47 UTC, jbubar commented on backend/controllers/project.controller.js
> +    console.log('pid: ', ProjectId);
Might want to remove this console.logs real quick

2021-08-18 15:22 UTC, jbubar commented on client/src/pages/ManageProjects.js
> -  const user = auth?.user;
Could this be a mistake?

2021-08-27 21:20 UTC, drubgrubby commented on client/src/pages/ManageProjects.js
> -  const user = auth?.user;
Yes, that could be a mistake.  That happened when trying to resolve a conflict.  Clearly conflict resolution isn't my strength.  I've replaced that and it resolved your very first comment.

2021-08-27 21:21 UTC, drubgrubby commented on backend/controllers/project.controller.js
> +    console.log('pid: ', ProjectId);
Done.

2021-08-27 21:27 UTC, drubgrubby commented on client/src/sass/ManageProjects.scss
> +.editable-field {
done

2021-08-27 21:32 UTC, drubgrubby commented on client/src/utils/fetchUtils.js
> +      if () {
Very good catch.  In fact it should break stuff, and it would if I was actually using this for anything.  It's something I made for later use, and later hasn't come yet.  I have deleted this file from the PR so we don't have to entertain the existential question of the empty if statement.

2021-08-27 23:10 UTC, drubgrubby commented
@jbubar -> I believe I have addressed your concerns.  If you could take another look it would be much appreciated.

2021-08-28 04:15 UTC, jbubar approved these changes
David! Great Work!
It has been really fun to see this pr get to this point. Major Kudos!
Everything works great on the edit-project page,
But there is one really important detail. When you go back to the manage projects page and click on the same project, it shows the old unedited information..
I sent you a video in slack.
We can do this in another pr.
But needs to be fixed soon.

2021-08-28 04:55 UTC, jbubar commented
Actually, I decided to fix it real quick....
You can see in the last commit.. bb67ae7

Want to review?

2021-08-29 13:57 UTC, drubgrubby commented
@jbubar -> Thanks so much for making the fix.  I have reviewed it and it works great!  Go team!  Please merge at your earliest convenience.

2021-08-30 16:08 UTC, merged