change nav to always show the same links
hackforla/VRMS pull request #774
Opened 2021-10-11 08:31 UTC by jbubar

fixes #698
Made it so that it always shows the same nav links no matter where you are on the site. 

I also got a little funky with the add events. 
In the issue there was no add events link in the nav, so I added a button to the events page on the bottom, and did some funky css, inkscape etc.

Here are the different nav links for each level of auth:
Not logged in: Home, Login
Admin: Home (goes to the admin stats dashboard thing),  Events, Admin, Projects
User: Projects

<details>
    <summary>CLICK ME to see a gif of the changes</summary>

![ezgif com-gif-maker](https://user-images.githubusercontent.com/53061723/136757290-790d27b1-5181-4317-a0e3-f6c785f8165b.gif)

</details>

Might also affect this one: #697

2021-10-11 08:37 UTC, jbubar commented
I also think that the user should be able to see the events page.. I also think we should add a search bar on the events page.. too many events

2021-10-11 23:58 UTC, drubgrubby requested changes
@jbubar -> Really nice work!  You really took the time to make the code better and cleaner than it was before.  And because you did that, it also will close another ticket, #697 . Wheeeee!

Two small changes: 

1) On the very cool "+ Add Event" animation.  Can you point that to /projects ?  The "add event" module is gone and people will be adding events through the Projects component. 

2) The login page when you first come to the site also shows the "Home" link. 
<img width="530" alt="Screen Shot 2021-10-11 at 4 39 46 PM" src="https://user-images.githubusercontent.com/68244054/136868576-958a78b4-2772-4e81-b0cd-75ad59f3de0c.png">

I think this page should only display the "login" link.

2021-10-14 21:17 UTC, drubgrubby approved these changes

2021-10-14 21:17 UTC, drubgrubby commented
@jbubar -> This looks great.  Nice work.  Ready to merge.

2021-10-14 21:18 UTC, merged